displayName: deepfake-detection-{job_id}

jobSpec:
  workerPoolSpecs:
    - machineSpec:
        machineType: n1-standard-4
        # Pending approval for GPU usage on Vertex AI. Uncomment the following lines to enable GPU usage.
        # acceleratorType: NVIDIA_TESLA_T4
        # acceleratorCount: 1
      replicaCount: 1
      containerSpec:
        imageUri: {image_uri}
        command:
          - uv
          - run
          - python
        args:
          - src/training/train.py
          - --job-id
          - "{job_id}"
        env:
          - name: GCP_PROJECT_ID
            value: deepfake-detection-ct0391